version: 2
updates:
  # Check python dependencies in services
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Check frontend npm packages
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # Check GitHub Actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
